services:
  servicea:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SERVICE_B_URL=http://serviceb:8002/

  serviceb:
    build: .
    command: uvicorn service_b.api_main:fastapi --host 0.0.0.0 --port 8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    environment:
      - SERVICE_A_URL=http://servicea:8000/

  celery_service_b:
    build: .
    command: celery -A service_b.worker worker -l info
    volumes:
      - .:/code
    environment:
      - SERVICE_A_URL=http://servicea:8000/
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
