# Generated by Django 3.2.12 on 2022-03-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('name', models.CharField(max_length=50, verbose_name='Человеко-понятное название задачи')),
                ('processing_time', models.PositiveIntegerField(verbose_name='Время выполнения в секундах')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новое'), (2, 'В процессе'), (3, 'Выполнено'), (4, 'Ошибка')], default=1, verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task',
            },
        ),
    ]
